course/course/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('first_app/', include('first_app.urls')),
    path('sec_app/', include('sec_app.urls')),
    path('third_app/', include('third_app.urls')),
    path('four_app/', include('four_app.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/first_app/urls.py
from django.conf.urls import url
from first_app import views
from django.urls import path

# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# ]

urlpatterns = [
    path('', views.index, name='index'),
]

course/four_app/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# ]

app_name = 'four_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

course/sec_app/urls.py
from django.conf.urls import url
from sec_app import views
from django.urls import path

# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# ]

urlpatterns = [
    path('', views.index, name='index'),
    path('form_page/', views.form_name_view, name='form_name'),
]

course/third_app/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# ]

# Template Tagging
app_name = 'third_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),
]

course/first_app/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

course/four_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

course/sec_app/models.py
from django.db import models

# Create your models here.

course/third_app/models.py
from django.db import models

# Create your models here.

course/four_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

course/sec_app/forms.py
from django import forms
from django.core import validators


# custom validation
# def check_for_z(value):
#     if value[0].lower() != 'z':
#         raise forms.ValidationError("name must be start with 0")


class FormName(forms.Form):
    # for custom validation use this
    # name = forms.CharField(validators=[check_for_z])

    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter Email again:")
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()  # to grab of all the fields of the form and it returns dictionary
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']
        if email != vmail:
            raise forms.ValidationError("Email doesn't match")

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("Gotcha bot!")
    #     return botcatcher

course/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic,Webpage,AccessRecord

# Create your views here.


def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {
        'access_records': webpages_list
    }
    # my_dict = {
    #     'insert_me': "hello i am from views.py !"
    # }
    return render(request, 'first_app/index.html', context=date_dict)

course/four_app/views.py
from django.shortcuts import render
from django.urls import reverse

from .forms import UserProfileInfoForm, UserForm


from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate

# Create your views here.


def index(request):
    return render(request, 'four_app/index.html')


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm
        profile_form = UserProfileInfoForm

    return render(request, "four_app/registration.html",
                            {
                                'user_form': user_form,
                                'profile_form': profile_form,
                                'registered': registered
                            })


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('four_app:index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'four_app/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('four_app:index'))


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

course/sec_app/views.py
from django.shortcuts import render
from . import forms
# Create your views here.


def index(request):
    return render(request, 'sec_app/index.html')


def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print(form.cleaned_data['name'])
            print(form.cleaned_data['email'])
            print(form.cleaned_data['text'])

    return render(request, 'sec_app/form_page.html', {'form': form})

course/third_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context_dict = {
        'text': 'hello world',
        'number': 100
    }
    return render(request, "third_app/index.html", context_dict)


def other(request):
    return render(request, "third_app/other.html")


def relative(request):
    return render(request, "third_app/relative.html")

course/templates/first_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First App</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}" >
</head>
<body>
    <h1>Hello this is index.html!</h1>
    <img src="{% static 'images/MedMan.jpg' %}" alt="didn't show">

    <h2>Here are your records:</h2>
    {% if access_records %}
        <table>
            <thead>
                <th>Site Name</th>
                <th>Date Accessed</th>
            </thead>
            {% for acc in access_records %}
                <tr>
                    <td>{{ acc.name }}</td>
                    <td>{{ acc.date }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>NO ACCESS RECORDS FOUND!</p>
    {% endif %}

</body>
</html>

course/templates/four_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'four_app:index' %}">DJANGO</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'four_app:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'four_app:logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'four_app:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

course/templates/four_app/index.html
{% extends "four_app/base.html" %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Django</h1>
    </div>
{% endblock %}

course/templates/four_app/login.html
{% extends 'four_app/base.html' %}

{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'four_app:user_login' %}" method="post">{% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login" name="">
    </form>
</div>
{% endblock %}

course/templates/four_app/registration.html
{% extends "four_app/base.html" %}

{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering</h1>
        {% else %}
            <h1>Register here!</h1>
            <h3>Fill out the form:</h3>
            <form method="post" enctype="multipart/form-data">  {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}

course/templates/sec_app/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">{% csrf_token %}
                         {{ form.as_p }}
                         <button type="submit" class="btn btn-default">Submit</button>
    </form>
</body>
</html>

course/templates/sec_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Welcome</h1>
</body>
</html>

course/templates/third_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'third_app:index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'third_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

course/templates/third_app/index.html
<!DOCTYPE html>
{% extends "third_app/base.html" %}

{% block body_block %}
    <h1>Welcome to index</h1>
    <h1>{{ text|upper }}</h1>
    <h1>{{ number|add:"99" }}</h1>
{% endblock %}

course/templates/third_app/other.html
<!DOCTYPE html>
{% extends "third_app/base.html" %}

{% block body_block %}
    <h1>Welcome to other</h1>
{% endblock %}

course/templates/third_app/relative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Welcome to relative</h1>
    <a href="{% url 'third_app:other' %}">go to other</a>
    <a href="{% url 'admin:index' %}">go to admin</a>
</body>
</html>